In [1]:
import theano
from theano import tensor as T, function

import numpy as np

Using gpu device 0: GeForce 940M (CNMeM is enabled with initial size: 80.0% of memory, cuDNN not available)


# Function definitions

In [2]:
X = T.matrix('x')
Y = X ** 2
F = function([X], [Y])

In [3]:
x = np.ones((2, 2)).astype('float32') * 3
print x

[[ 3.  3.]
 [ 3.  3.]]


In [4]:
y = F(x)
print y

[array([[ 9.,  9.],
       [ 9.,  9.]], dtype=float32)]


In [12]:
Z = T.grad(Y.sum(), X)
G = function([X], [Y, Z])

In [13]:
y, z = G(x)
print y
print z

[[ 9.  9.]
 [ 9.  9.]]
[[ 6.  6.]
 [ 6.  6.]]


# Symbolic vs Shared variables in Theano

In [15]:
X

x

In [16]:
X_shared = theano.shared(np.ones((3,3)))

In [17]:
X_shared.get_value()

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])